### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by mfoglio** [daltonfury42/truecase#13]
After installing the package I get:

`ModuleNotFoundError: No module named 'truecase'
`
on 
`
import truecase`

**Comment by danyaljj** [comment]
Same error here; odd.

**Comment by daltonfury42** [comment]
The issue has been fixed, `pip3 install --upgrade truecase` to update to latest version.

@danyaljj @mfoglio Thanks a lot for reporting.
