### ISSUE TITLE
Incorrect handling of contractions

### ISSUE THREAD

**Issue by jayargo** [daltonfury42/truecase#6]
correctedStr = truecase.get_true_case("I didn't get the best price.")
print(correctedStr)
> I did n't get the best price.

correctedStr = truecase.get_true_case("I don't want another.")
print(correctedStr)
> I do n't want another.

**Comment by sergialonsaco** [comment]
fixed in PR: https://github.com/daltonfury42/truecase/pull/8, using Tweettokenize instead of word_tokenize should be enough to fix the problem.

**Comment by daltonfury42** [comment]
@sergialonsaco Thanks for the fix. Verified. Closing the PR.
```
>>> truecase.get_true_case("I didn't get the best price.")
"I didn't get the best price."
```

@jayargo New package has been uploaded to PIP. Thanks for raising the issue.
